# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: dapr-helm-to-acr

on:
  push:
    branches:
      - master

jobs:
  test-e2e:
    name: helm chart upload
    runs-on: ubuntu-latest
    env:
      GOVER: 1.14
      GOOS: linux
      GOARCH: amd64
      GOPROXY: https://proxy.golang.org
      DAPR_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      DAPR_TEST_REGISTRY: ${{ secrets.DOCKER_TEST_REGISTRY }}
      HELMVER: v3.0.3
      DAPR_NAMESPACE: dapr-tests
      MAX_TEST_TIMEOUT: 5400
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ env.GOVER }}
      - name: Set env variables
        run: |
          echo ::set-env name=CHECKOUT_REPO::${{ github.repository }}
          echo ::set-env name=CHECKOUT_REF::refs/heads/master
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: ${{ env.CHECKOUT_REPO }}
          ref: ${{ env.CHECKOUT_REF }}
      - name: Parse release version and set REL_VERSION
        run: |
          python ./.github/scripts/get_release_version.py
          echo ::set-env name=DAPR_VERSION::"edge"
      - name: Set up Helm ${{ env.HELMVER }}
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELMVER }}
      - name: Upload Helm charts to ACR
        run: |
          export HELM_EXPERIMENTAL_OCI=1
          echo ${{ secrets.SP_PASSWD }} | helm registry login ${{ secrets.ACR_NAME }} --username ${{ secrets.SP_APP_ID }} --password-stdin
          make upload-helmchart
